remote_theme: BDHU/minimalist@23d0af215786e0249f853b856cef4ea029704ff3
plugins:
- jekyll-remote-theme # add
title: Giorgio Cefaro |  Engineering Leader
logo: /giorgio.jpg
description: Engineering Leader | Helping organizations scale tech & talent
show_downloads: false
sidebar:
  - name: Linkedin
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/giorgiocefaro
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/giorrrgio
  - name: Twitter
    icon: <i class="fa-brands fa-twitter"></i>
    link: https://twitter.com/giorrrgio
