remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add
title: Giorgio Cefaro
logo: /giorgio.jpg
description: Senior Software Development Manager @ Hootsuite
show_downloads: false

navbar-links:
  home: "index"
  linkedin: "https://www.linkedin.com/in/giorgiocefaro"
  twitter: "https://twitter.com/giorrrgio"
  instagram: "https://www.instagram.com/giorrrgio/"
